name: ci-cd pipeline
on: [push]


jobs:
  express-login-logout:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci

      - name: build
        run: npm run build

      - name: Start the server 
        run: npm start & sleep 5

      - name: test 
        run: npm test & sleep 5
  
        
  




